name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install bevy linux dependencies
      run: sudo apt-get update && sudo apt-get install libasound2-dev
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --color always --all-targets --all-features  
    - name: Check formatting
      run: cargo fmt --all --check -- --color=always
